### ISSUE TITLE
v0.5.1 on npm doesn't have an entry point

### ISSUE THREAD

**Issue by yortus** [albe/node-event-storage#28]
Hi, I'm evaluating this library for event sourcing and noticed that v0.5.1 as published on npm doesn't have an entry point, so `require('event-storage')` fails.

I then tried installing v0.5.0 from npm, and that version works fine.

For some reason npm is lacking the root `index.js` file in the published version of v0.5.1.

**Comment by albe** [comment]
Thanks for the hint, I will have a look asap.

**Comment by albe** [comment]
Fixed with v0.5.2
